### ISSUE TITLE
Ember Truth Helper

### ISSUE THREAD

**Issue by btecu** [clairton/is-equal#1]
This addon does something very similar:
https://github.com/jmurphyau/ember-truth-helpers

**Comment by clairton** [comment]
Does it work in ember 2.0? this it works.
But I remember-me this for now (is-equal and eq).

**Comment by btecu** [comment]
Yes, it works.

**Comment by btecu** [comment]
Also, unrelated but I noticed `text-concat` addon. Ember has this functionality already, just use the helper `concat`.

http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_concat

**Comment by clairton** [comment]
Addon concat-text was for ember < 1.13, for now can be deprecated.

Thank's
